spring:
  datasource: #http://localhost:8090/h2-console/
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true



server:
  port: 8090