spring:
  datasource: #http://localhost:8090/h2-console/
    url: jdbc:h2:mem:testdb #jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8090

logging.level:
  org.hibernate:
    SQL: debug
    type: trace